# This is the config file for landscape.io
# https://landscape.io/pages/docs
# https://landscape.io/github/astropy/imageutils

ignore-paths:
  - migrations/

pylint:
  disable:
    - unused-argument

requirements:
    - estagio/docs/requirements.txt

python-targets:
    - 3